name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run your script and capture output
        run: |
          python crypto_tracker_me_trends2.py | tee output.log

      - name: Send Email with Log Output
        uses: mendhak/send-email@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Bitcoin Tracker Output"
          body: "See attached log file"
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.EMAIL_USER }}
          attachments: output.log


